Add a little script that prints out invalid users in the db
Stellar-Quest-Lumenauts/fantastic-goggles pull request #17
Opened 2021-05-21 15:37 UTC by Smephite

prints all users in `votes_history` not being a Lumenaut and puts them into WHERE clause to use in _live_ production databases ;)

2021-05-22 01:37 UTC, w00kie commented
Sorry, I think that because of our little issue with my work account and the rebasing, it messed up your pull request. You might have to redo it 😓

2021-05-23 11:58 UTC, MatejMecka requested changes
Just one little thing

2021-05-23 11:58 UTC, MatejMecka commented on handle_clean_db.py
> +    guild = client.get_guild(763798356484161566)
Can it be an env Variable?

2021-05-24 11:27 UTC, MatejMecka approved these changes
LGTM!

2021-05-24 11:27 UTC, merged